spring:
  output:
    ansi:
      enabled: always
  application:
   name: afristays
  cloud:
    gateway:
      routes:
        - id: test-route
          uri: https://httpbin.org
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:*"
              - "https://localhost:*"
              - "http://server.trevtechltd.com:*"
              - "https://server.trevtechltd.com:*"
              - "https://www.afristays.com"
              - "https://afristays.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - Authorization
              - Content-Type
            maxAge: 3600

server:
  port: 31304
  address: 0.0.0.0  # Allow external access
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: Ashihundu@2003
    key-store-type: PKCS12
    key-alias: tomcat

# Enable actuator endpoints for debugging
management:
  endpoints:
    web:
      exposure:
        include: health,gateway,metrics,loggers
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    com.afristays.apigateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.http.server.reactive: DEBUG
    REQUEST_LOGGER: INFO
    RESPONSE_LOGGER: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId:-}] [%X{clientIp:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId:-}] [%X{clientIp:-}] %logger{36} - %msg%n"
  file:
    name: logs/afristays-gateway.log
